### ISSUE TITLE
UWP C++ Rewarded Ads not get

### ISSUE THREAD

**Issue by range-vs** [Vungle/Windows-SDK#45]
Greetings. Now I'm running simple tests of running rewarded ads.
I compiled your example for a UWP C++ application, replaced app_id and placement_id with my own.
SDK initialization successful. Next, I try to load an ad:
`    sdkInstance->LoadAd(ref new Platform::String(std::wstring(placement3.begin(), placement3.end()).c_str()));`
I get the following error:
`    Diagnostics: Error VungleSDK.VungleAd Windows.Foundation.IReference1<Windows.Foundation.HResult> Don't use LoadAd() for Header Bidding Ads. Instead, use LoadMediatedAd()`
I went to the Vungle dashboard and disabled In-App Bidding:
![image_2024-02-08_14-26-07](https://github.com/Vungle/Windows-SDK/assets/31132096/af405084-1db2-4409-a218-e7ab80e1077f)
The SDK behavior has changed when calling the method:
`    sdkInstance->LoadAd(ref new Platform::String(std::wstring(placement3.begin(), placement3.end()).c_str()));`
I don't get any ads as if they're not available. I tried several countries but still couldn't get any ads.
My application statuses and placement_id:
![image_2024-02-08_14-29-55](https://github.com/Vungle/Windows-SDK/assets/31132096/2190a377-7768-4458-8876-6db569b47f40)
![image_2024-02-08_14-29-39](https://github.com/Vungle/Windows-SDK/assets/31132096/b220acce-cc61-4e72-8ccb-c09010934f05)
What can be checked and corrected? Thank you.

**Comment by gregthatcher** [comment]
Hi @range-vs ,

Yes, you have correctly turned off "In-App bidding", but you may need to wait for some time for all of our servers to update with the change.

Also, it might also be a good idea to uninstall and then reinstall your application, as our SDK "remembers" when it has problems downloading ads, and may make you wait longer before it actually requests a new ad.

If this doesn't work, you might try deleting all thee files in this directory while your application is _not_ running  : 
C:\Users\<your user name>\AppData\Local\Packages\<mangled name of your app's package>\LocalState\VungleSDK
After deleting these files, re-run the application.

If you have any further problems, please send me your Vungle Application id, so that I can debug further.  If you don't feel comfortable posting your application id here, you can email me at gthatcher "at" liftoff.io.

**Comment by range-vs** [comment]
@gregthatcher Hi!

Okay, I'll try your recommendations next week and come back with the results later.

**Comment by range-vs** [comment]
@gregthatcher 
Greetings. I'm coming back with feedback, as promised. On some PCs I am seeing the following error:
`LoadAd: Can't load placement "PLACEMENT_ID" because it is sleeping`
But for some everything is fine. What could be the problem?

**Comment by gregthatcher** [comment]
Hi @range-vs , sometimes, our platform can't find a suitable ad to show because of various reasons (not enough ad supply at that moment and price point, advertisers don't want to spend on your geo or user, user has already seen too many ads recently, etc.)

When this happens, the SDK (running inside your application) receives a "sleep" code, telling the SDK that it shouldn't try to load another ad for that placement for some specific amount of time.

If you believe that a given Placement is _never_  able to load an add, send me the placement id and your app id, and I can check your configuration to see if something is wrong.

**Comment by range-vs** [comment]
Hi @gregthatcher. 

> If you believe that a given Placement is never able to load an add, send me the placement id and your app id, and I can check your configuration to see if something is wrong.

I would not like to publish this in the public domain. Where can I send it?

**Comment by gregthatcher** [comment]
Very sorry for the delay in responding, @range-vs .  You can send it to gthatcher "at" liftoff.io

**Comment by range-vs** [comment]
@gregthatcher hello! I send info to your email address :)

**Comment by gregthatcher** [comment]
Hi @range-vs,

Sorry for the delay in getting back to you.  Using your app id, the rewarded placement ("VUNGLE-REWARD...") is automatically loading (because it is auto-cached), and seems to play with no problems.

Have your problems resolved, or would you like me to investigate further?

**Comment by range-vs** [comment]
Hello @gregthatcher 
No, my promlem is solved. Thanks!
